services:
  node-dev:
    image: node:20-alpine
    container_name: penny-dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "9002:9002"  
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"

  postgres:
    image: postgres:15-alpine
    container_name: penny-postgres
    environment:
      - POSTGRES_USER=penny
      - POSTGRES_PASSWORD=p33nyAdmin
      - POSTGRES_DB=pennydb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
