services:
  nodeapp:
    # image: node:20-alpine
    build:
      context: .
      dockerfile: Dockerfile
    container_name: penny
    restart: always
    # working_dir: /app
    # volumes:
    #   - .:/app
    ports:
      - "9002:3000"  
    # command: sh -c "npm install && npm run dev"

  postgres:
    image: postgres:15-alpine
    container_name: penny-postgres
    restart: always
    environment:
      - POSTGRES_USER=penny
      - POSTGRES_PASSWORD=p33nyAdmin
      - POSTGRES_DB=pennydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
